Documentaion_FileName_check.sh added

diff --git a/.github/workflows/json-check.yml b/.github/workflows/json-check.yml
--- a/.github/workflows/json-check.yml
+++ b/.github/workflows/json-check.yml
@@ -34,4 +34,39 @@ jobs:
           fi
         shell: bash -l {0} -v
 
+  json-documentation-check:
+    runs-on: ubuntu-latest
+    needs: json-syntax-validation
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Check changed files
+        uses: dorny/paths-filter@v3
+        id: filter
+        with:
+          filters: |
+            json: '**/*.json'
+
+      - name: Run Documentation FileName Check
+        # if: steps.filter.outputs.json == 'true'
+        run: |
+          git fetch origin main
+          errors=0
+          for file in $(git diff --name-only origin/main...HEAD -- '*.json') ; do
+            ./Documentation_FileName_check.sh "$file"
+            if [ $? -ne 0 ]; then
+              ((errors++))
+            fi
+          done
+          if ((errors)); then
+            echo "$errors files had documentation file name errors"
+            exit 1
+          fi
+        shell: bash -l {0} -v
+
+
+
       
